meson: Fix missing dependency from install-quiet to sepgsql.sql
This could lead to an error like

ERROR: File 'contrib/sepgsql/sepgsql.sql' could not be found

Backpatch: 16-, where meson was added
(cherry picked from commit 823eb3db1c50a6b8a89ebedc1db96b14de140183)